config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  namespace :admin do
    get 'dashboard/main'
    get 'dashboard/user'
    get 'dashboard/blog'
  end
  resources :portfolios, except: [:show]
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :bloggs do
    member do
      get :toggle_status
    end
  end

  resources :bloggs
  resources :posts
  root to: 'pages#home'

  get 'posts/*missing', to: 'posts#missing'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blogg.rb
class Blogg < ApplicationRecord
  enum status: {draft: 0, published: 1}
  extend FriendlyId
  friendly_id :title, use: :slugged
  validates_presence_of :title, :body
  belongs_to :topic
end

app/models/concerns/placeholder.rb
module Placeholder
  extend ActiveSupport::Concern

  def self.imageGenerator(height:, width:)
    "https://via.placeholder.com/#{height}x#{width}"
  end
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies,
                                reject_if: lambda{|attrs| attrs['name'].blank?}
  include Placeholder
  validates_presence_of :title, :body, :main_image, :thumb_image

  scope :angular_portfolio_items, -> {where(subtitle: 'Angular')}
  scope :ruby_on_rails_portfolio_items, -> {where(subtitle: 'Ruby on Rails')}

  after_initialize :set_defaults

  def set_defaults
    self.main_image ||= Placeholder.imageGenerator(height: '600', width: '400')
    self.thumb_image ||= Placeholder.imageGenerator(height: '350', width: '200')
  end
end

app/models/skill.rb
class Skill < ApplicationRecord
  include Placeholder
  validates_presence_of :title, :percent_utilized

  after_initialize :set_defaults

  def set_defaults
    self.badge ||= Placeholder.imageGenerator(height: '250', width: '250')
  end
end

app/models/technology.rb
class Technology < ApplicationRecord
  belongs_to :portfolio
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates_presence_of :title
  has_many :bloggs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_presence_of :name
  def first_name
    self.name.split.first
  end

  def last_name
    self.name.split.last
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  def main
  end

  def user
  end

  def blog
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include DeviseWhitelist
  include SetSource
  include CurrentUserConcern
  include DefaultPageContent

end

app/controllers/bloggs_controller.rb
class BloggsController < ApplicationController
  before_action :set_blogg, only: [:show, :edit, :update, :destroy, :toggle_status]
  layout "blog"

  # GET /bloggs
  # GET /bloggs.json
  def index
    @bloggs = Blogg.all
    @page_title = "My Portfolio Blog"
  end

  # GET /bloggs/1
  # GET /bloggs/1.json
  def show
    @page_title = @blogg.title
    @seo_keywords = @blog.body
  end

  # GET /bloggs/new
  def new
    @blogg = Blogg.new
  end

  # GET /bloggs/1/edit
  def edit
  end

  # POST /bloggs
  # POST /bloggs.json
  def create
    @blogg = Blogg.new(blogg_params)

    respond_to do |format|
      if @blogg.save
        format.html { redirect_to @blogg, notice: 'Blogg was successfully created.' }
        format.json { render :show, status: :created, location: @blogg }
      else
        format.html { render :new }
        format.json { render json: @blogg.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bloggs/1
  # PATCH/PUT /bloggs/1.json
  def update
    respond_to do |format|
      if @blogg.update(blogg_params)
        format.html { redirect_to @blogg, notice: 'Blogg was successfully updated.' }
        format.json { render :show, status: :ok, location: @blogg }
      else
        format.html { render :edit }
        format.json { render json: @blogg.errors, status: :unprocessable_entity }
      end
    end
  end

  def toggle_status
    if @blogg.draft?
      @blogg.published!
    elsif @blogg.published?
      @blogg.draft!
    end
    redirect_to bloggs_url, notice: 'Post status has been updated.'
  end

  # DELETE /bloggs/1
  # DELETE /bloggs/1.json
  def destroy
    @blogg.destroy
    respond_to do |format|
      format.html { redirect_to bloggs_url, notice: 'Blogg was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blogg
      @blogg = Blogg.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blogg_params
      params.require(:blogg).permit(:title, :body)
    end
end

app/controllers/concerns/current_user_concern.rb
module CurrentUserConcern
  extend ActiveSupport::Concern
  def current_user
    super || guest_user
  end

  def guest_user
    OpenStruct.new(name: "Guest User",
                   first_name: "Guest",
                   last_name: "User",
                   email: "guest@example.com")
  end
end

app/controllers/concerns/default_page_content.rb
module DefaultPageContent
  extend ActiveSupport::Concern

  included do
    before_action :set_page_defaults
  end

  def set_page_defaults
    @page_title = "Devcamp Portfolio | My Portfolio Website"
    @seo_keywords = "Benovskyi Bohdan portfolios"
  end
end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
  extend ActiveSupport::Concern

  included do
    before_action :configure_permitted_parameters, if: :devise_controller?
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/concerns/set_source.rb
module SetSource
  extend ActiveSupport::Concern

  included do
    before_action :set_source
  end

  def set_source
    session[:source] = params[:q] if params[:q]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @skills = Skill.all
    @posts = Blogg.all
  end

  def about
  end

  def contact
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  layout "portfolio"
  def index
    @portfolio_items = Portfolio.all
  end

  def angular
    @angular_portfolio_items = Portfolio.angular_portfolio_items
  end

  def new
    @portfolio_item = Portfolio.new
    3.times{@portfolio_item.technologies.build}
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'Your portfolio item is now live.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    @portfolio_item = Portfolio.find(params[:id])
  end

  def update
    @portfolio_item = Portfolio.find(params[:id])

    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'Record was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def show
    @portfolio_item = Portfolio.find(params[:id])
  end

  def destroy
    #Perform the lookup
    @portfolio_item = Portfolio.find(params[:id])

    #Destroy/delete the record
    @portfolio_item.destroy

    #Redirect
    respond_to do |format|
      format.html { redirect_to bloggs_url, notice: 'Record was removed' }
    end
  end

  private
  def portfolio_params
    params.require(:portfolio).permit(:title,
                                      :subtitle,
                                      :body,
                                      technologies_attributes: [:name]
                                    )
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index

  end

  def missing

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bloggs_helper.rb
module BloggsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/bloggs/_form.html.erb
<%= form_with(model: blogg, local: true) do |form| %>
  <% if blogg.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blogg.errors.count, "error") %> prohibited this blogg from being saved:</h2>

      <ul>
      <% blogg.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bloggs/edit.html.erb
<h1>Editing Blogg</h1>

<%= render 'form', blogg: @blogg %>

<%= link_to 'Show', @blogg %> |
<%= link_to 'Back', bloggs_path %>

app/views/bloggs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bloggs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bloggs.each do |blogg| %>
      <tr>
        <td><%= blogg.title %></td>
        <td><%= blogg.body %></td>
        <td><%= link_to blogg.status, toggle_status_blogg_path(blogg) %></td>
        <td><%= link_to 'Show', blogg %></td>
        <td><%= link_to 'Edit', edit_blogg_path(blogg) %></td>
        <td><%= link_to 'Destroy', blogg, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blogg', new_blogg_path %>

app/views/bloggs/new.html.erb
<h1>New Blogg</h1>

<%= render 'form', blogg: @blogg %>

<%= link_to 'Back', bloggs_path %>

app/views/bloggs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blogg.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blogg.body %>
</p>

<%= link_to 'Edit', edit_blogg_path(@blogg) %> |
<%= link_to 'Back', bloggs_path %>

app/views/portfolios/angular.html.erb
<h1>Angular portfolio items</h1>

<%= link_to "Create New Item", new_portfolio_url %>

<% @angular_portfolio_items.each do |portfolio_item| %>
  <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item.id)%></p>
  <p><%= portfolio_item.subtitle%></p>
  <p><%= portfolio_item.body%></p>
  <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil?%>
  <%= link_to "Edit", edit_portfolio_path(portfolio_item.id) %>
  <%= link_to 'Delete portfolio item', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/portfolios/edit.html.erb
<h1>Edit this portfolio item</h1>

<%= form_for(@portfolio_item) do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/index.html.erb
<h1>Portfolio items</h1>

<%= link_to "Create New Item", new_portfolio_url %>

<% @portfolio_items.each do |portfolio_item| %>
  <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item.id)%></p>
  <p><%= portfolio_item.subtitle%></p>
  <p><%= portfolio_item.body%></p>
  <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil?%>
  <%= link_to "Edit", edit_portfolio_path(portfolio_item.id) %>
  <%= link_to 'Delete portfolio item', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/portfolios/new.html.erb
<h1>Create a new portfolio item</h1>

<%= form_for(@portfolio_item) do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <ul>
    <%= form.fields_for :technologies do |technology_form| %>
      <li>
        <%= technology_form.label :name%>
        <%= technology_form.text_field :name%>
      </li>
    <% end %>
  </ul>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/show.html.erb
<%= image_tag  @portfolio_item.main_image unless @portfolio_item.main_image.nil?%>

<h1><%= @portfolio_item.title %></h1>

<em><%= @portfolio_item.subtitle %></em>

<p><%= @portfolio_item.body %></p>

<h2>Technologies used: </h2>

<% @portfolio_item.technologies.each do |t|%>
  <p><%= t.name %></p>
<% end %>