config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  namespace :admin do
    get 'dashboard/main'
    get 'dashboard/user'
    get 'dashboard/blog'
  end
  resources :portfolios, except: [:show]
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :bloggs do
    member do
      get :toggle_status
    end
  end

  resources :bloggs
  resources :posts
  root to: 'pages#home'

  get 'posts/*missing', to: 'posts#missing'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blogg.rb
class Blogg < ApplicationRecord
  enum status: {draft: 0, published: 1}
  extend FriendlyId
  friendly_id :title, use: :slugged
  validates_presence_of :title, :body
  belongs_to :topic
end

app/models/concerns/placeholder.rb
module Placeholder
  extend ActiveSupport::Concern

  def self.imageGenerator(height:, width:)
    "https://via.placeholder.com/#{height}x#{width}"
  end
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies,
                                reject_if: lambda{|attrs| attrs['name'].blank?}
  include Placeholder
  validates_presence_of :title, :body, :main_image, :thumb_image

  scope :angular_portfolio_items, -> {where(subtitle: 'Angular')}
  scope :ruby_on_rails_portfolio_items, -> {where(subtitle: 'Ruby on Rails')}

  after_initialize :set_defaults

  def set_defaults
    self.main_image ||= Placeholder.imageGenerator(height: '600', width: '400')
    self.thumb_image ||= Placeholder.imageGenerator(height: '350', width: '200')
  end
end

app/models/skill.rb
class Skill < ApplicationRecord
  include Placeholder
  validates_presence_of :title, :percent_utilized

  after_initialize :set_defaults

  def set_defaults
    self.badge ||= Placeholder.imageGenerator(height: '250', width: '250')
  end
end

app/models/technology.rb
class Technology < ApplicationRecord
  belongs_to :portfolio
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates_presence_of :title
  has_many :bloggs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_presence_of :name
  def first_name
    self.name.split.first
  end

  def last_name
    self.name.split.last
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include DeviseWhitelist
  include SetSource
  include CurrentUserConcern
  include DefaultPageContent

end

app/controllers/bloggs_controller.rb
class BloggsController < ApplicationController
  before_action :set_blogg, only: [:show, :edit, :update, :destroy, :toggle_status]
  layout "blog"

  # GET /bloggs
  # GET /bloggs.json
  def index
    @bloggs = Blogg.all
    @page_title = "My Portfolio Blog"
  end

  # GET /bloggs/1
  # GET /bloggs/1.json
  def show
    @page_title = @blogg.title
    @seo_keywords = @blog.body
  end

  # GET /bloggs/new
  def new
    @blogg = Blogg.new
  end

  # GET /bloggs/1/edit
  def edit
  end

  # POST /bloggs
  # POST /bloggs.json
  def create
    @blogg = Blogg.new(blogg_params)

    respond_to do |format|
      if @blogg.save
        format.html { redirect_to @blogg, notice: 'Blogg was successfully created.' }
        format.json { render :show, status: :created, location: @blogg }
      else
        format.html { render :new }
        format.json { render json: @blogg.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bloggs/1
  # PATCH/PUT /bloggs/1.json
  def update
    respond_to do |format|
      if @blogg.update(blogg_params)
        format.html { redirect_to @blogg, notice: 'Blogg was successfully updated.' }
        format.json { render :show, status: :ok, location: @blogg }
      else
        format.html { render :edit }
        format.json { render json: @blogg.errors, status: :unprocessable_entity }
      end
    end
  end

  def toggle_status
    if @blogg.draft?
      @blogg.published!
    elsif @blogg.published?
      @blogg.draft!
    end
    redirect_to bloggs_url, notice: 'Post status has been updated.'
  end

  # DELETE /bloggs/1
  # DELETE /bloggs/1.json
  def destroy
    @blogg.destroy
    respond_to do |format|
      format.html { redirect_to bloggs_url, notice: 'Blogg was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blogg
      @blogg = Blogg.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blogg_params
      params.require(:blogg).permit(:title, :body)
    end
end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
  extend ActiveSupport::Concern

  included do
    before_action :configure_permitted_parameters, if: :devise_controller?
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/concerns/set_source.rb
module SetSource
  extend ActiveSupport::Concern

  included do
    before_action :set_source
  end

  def set_source
    session[:source] = params[:q] if params[:q]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @skills = Skill.all
    @posts = Blogg.all
  end

  def about
  end

  def contact
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  layout "portfolio"
  def index
    @portfolio_items = Portfolio.all
  end

  def angular
    @angular_portfolio_items = Portfolio.angular_portfolio_items
  end

  def new
    @portfolio_item = Portfolio.new
    3.times{@portfolio_item.technologies.build}
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'Your portfolio item is now live.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    @portfolio_item = Portfolio.find(params[:id])
  end

  def update
    @portfolio_item = Portfolio.find(params[:id])

    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'Record was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def show
    @portfolio_item = Portfolio.find(params[:id])
  end

  def destroy
    #Perform the lookup
    @portfolio_item = Portfolio.find(params[:id])

    #Destroy/delete the record
    @portfolio_item.destroy

    #Redirect
    respond_to do |format|
      format.html { redirect_to bloggs_url, notice: 'Record was removed' }
    end
  end

  private
  def portfolio_params
    params.require(:portfolio).permit(:title,
                                      :subtitle,
                                      :body,
                                      technologies_attributes: [:name]
                                    )
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index

  end

  def missing

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bloggs_helper.rb
module BloggsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="keywords" content="<%= @seo_keywords %>" />

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= render "shared/nav" %>

    <%if current_user.is_a?(User) %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <%else %>
      <%= link_to "Register", new_user_registration_path%>
      <%= link_to "Login", new_user_session_path%>
    <%end %>
    <%= yield %>

    <% if session[:source] %>
      <p>Thanks for visiting me from <%= session[:source] %></p>
    <% end %>
  </body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta name="keywords" content="<%= @seo_keywords %>" />

  <%= stylesheet_link_tag    'bloggs', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%if current_user.is_a?(User) %>
  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
<%else %>
  <%= link_to "Register", new_user_registration_path%>
  <%= link_to "Login", new_user_session_path%>
<%end %>
<%= yield %>

<%= render "shared/nav" %>

<% if session[:source] %>
  <p>Thanks for visiting me from <%= session[:source] %></p>
<% end %>
</body>
</html>

app/views/layouts/portfolio.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta name="keywords" content="<%= @seo_keywords %>" />

  <%= stylesheet_link_tag    'portfolios', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%if current_user.is_a?(User) %>
  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
<%else %>
  <%= link_to "Register", new_user_registration_path%>
  <%= link_to "Login", new_user_session_path%>
<%end %>
<%= yield %>

<%= render "shared/nav" %>

<% if session[:source] %>
  <p>Thanks for visiting me from <%= session[:source] %></p>
<% end %>
</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Hi, <%= current_user.first_name%></h1>
<p>Find me in app/views/pages/home.html.erb</p>

<h1>Blog Posts</h1>
<%= @posts.inspect %>

<h1>Skills</h1>
<%= @skills.inspect %>

app/views/shared/_nav.html.erb
<div>
  <div><%= link_to "Home", root_path %></div>
  <div><%= link_to "About me", about_me_path %></div>
  <div><%= link_to "Contact", contact_path %></div>
  <div><%= link_to "Blog", bloggs_path %></div>
  <div><%= link_to "Portfolio", portfolios_path %></div>
</div>